export default {
  "services.applocale.lang.en": "English",
  "services.applocale.lang.tl": "Tagalog",
  "components.gui.langctrl.label": "Language",
  
  "btn.save": "Save",
  "btn.cancel": "Cancel",
  "btn.edit": "Edit",
  "btn.add": "Add",
  
  "screens.screen001.title": "Users",
  "screens.screen001.profile.nouser": "User Profile",
  "screens.screen001.profile.hasuser": "{0}'s Profile",
  "screens.screen001.otherdetails": "Other Details",
  "screens.screen001.username": "Username",
  "screens.screen001.pwd": "Password",
  "screens.screen001.fname": "First Name",
  "screens.screen001.lname": "Last Name",
  "screens.screen001.gender": "Gender",
  "screens.screen001.bday": "Birthday",
  "screens.screen001.pwd.placeholder": "Must contain one letter, one number and one symbol",
  "screens.screen001.bday.placeholder": "yyyy/mm/dd",
  "screens.screen001.gender.lookup.m": "Male",
  "screens.screen001.gender.lookup.f": "Female",
  
  "modal.modal001a.title": "New Component",
  "modal.modal001a.label": "Label",
  "modal.modal001a.type": "Control Type",
  "modal.modal001a.mandatory": "Mandatory",
  "modal.modal001a.minlength": "Min Length",
  "modal.modal001a.maxlength": "Max Length",
  "modal.modal001a.placeholder": "Placeholder",
  "modal.modal001a.options": "Options",
  "modal.modal001a.options.placeholder": "Options should be separated by row",
  "modal.modal001a.type.lookup.t": "Text",
  "modal.modal001a.type.lookup.r": "Radio",
  "modal.modal001a.type.lookup.d": "Date",
  "modal.modal001a.mandatory.lookup.y": "Yes",
  "modal.modal001a.mandatory.lookup.n": "No",
  
  "error.required": "{0} must be specified.",
  "error.minlength": "{0} must have length greater than or equal to {1}, current length is {2}.",
  "error.maxlength": "{0} must have length lesser than or equal to {1}, current length is {2}.",
  "error.invalidpwdformat": "{0} does not follow the required format. Must contain one letter, one number and one symbol.",
  "error.dateformat": "{0} does not follow the required format. Please use {1} format.",
  "error.invalidnumberformat": "{0} should be a number."
};