export default {
  "services.applocale.lang.en": "Ingles",
  "services.applocale.lang.tl": "Tagalog",
  "components.gui.langctrl.label": "Lenggwahe",
  
  "btn.save": "Salbahin",
  "btn.cancel": "Kanselahin",
  "btn.edit": "Baguhin",
  "btn.add": "Dagdagan",
  
  "screens.screen001.title": "Mga Taga-gamit",
  "screens.screen001.profile.nouser": "Profile ng Taga-gamit",
  "screens.screen001.profile.hasuser": "Profile ni {0}",
  "screens.screen001.otherdetails": "Ibang Detalye",
  "screens.screen001.username": "Username",
  "screens.screen001.pwd": "Password",
  "screens.screen001.fname": "Unang Pangalan",
  "screens.screen001.lname": "Huling Pangalan",
  "screens.screen001.gender": "Kasarian",
  "screens.screen001.bday": "Kaarawan",
  "screens.screen001.pwd.placeholder": "Kailangan ng isang letra, isang numero at isang symboliko",
  "screens.screen001.bday.placeholder": "yyyy/mm/dd",
  "screens.screen001.gender.lookup.m": "Lalaki",
  "screens.screen001.gender.lookup.f": "Babae",
  
  "modal.modal001a.title": "Bagong Komponent",
  "modal.modal001a.label": "Tanda",
  "modal.modal001a.type": "Klase ng Kontrol",
  "modal.modal001a.mandatory": "Sapilitan",
  "modal.modal001a.minlength": "Min Haba",
  "modal.modal001a.maxlength": "Max Haba",
  "modal.modal001a.placeholder": "Plaseholder",
  "modal.modal001a.options": "Mga Opsyon",
  "modal.modal001a.options.placeholder": "Ang mga opsyon ay dapat nakahiwalay ayon sa hilera",
  "modal.modal001a.type.lookup.t": "Teksto",
  "modal.modal001a.type.lookup.r": "Radio",
  "modal.modal001a.type.lookup.d": "Petsa",
  "modal.modal001a.mandatory.lookup.y": "Oo",
  "modal.modal001a.mandatory.lookup.n": "Hindi",
  
  "error.required": "Ang {0} ay kailangan.",
  "error.minlength": "Ang {0} ay kailangan mas mahaba or pantay sa {1}, kasalukuyang haba ay {2}.",
  "error.maxlength": "Ang {0} ay kailangan mas maikli or pantay sa {1}, kasalukuyang haba ay {2}.",
  "error.invalidpwdformat": "Ang {0} ay hindi sumusunod sa tamang format. Kailangan ng isang letra, isang numero at isang symboliko.",
  "error.dateformat": "Ang {0} ay hindi sumusunod sa tamang format. Paki-gamit ng {1} na format.",
  "error.invalidnumberformat": "Ang {0} ay dapat numero."
};